includes/class-wc-custom-order-table-install.php
tests/test-installation.php
tests/testcase.php
wc-custom-order-table.php

This PR rewrites the `WC_Custom_Order_Table_Install` to use just two static methods: `activate()` (which performs the jobs formerly handled by `maybe_install_tables()`, `get_latest_table_version()`, and `get_installed_table_version()`), and `install_tables()`, the latter of which is marked as protected.
This enables `register_activation_hook()` to call `WC_Custom_Order_Table_Install::activate()` directly, while avoiding treating the installer as an object (since it's really just using the class construct as a pseudo-namespace).
The PR also ensures that the "wc_orders_table_version" option is not auto-loaded, as it's _only_ needed during plugin activation.

Cleanup the table installation script

---

CHANGELOG.md
CONTRIBUTING.md
wc-custom-order-table.php

This pull request introduces two new files:
1. `CHANGELOG.md` tracks changes as they're made between releases (I've retroactively added a changeset for 1.0.0 Betas 1 to 2), based on the [Keep a Changelog standard](http://keepachangelog.com/en/1.0.0/).
2. `CONTRIBUTING.md` covers coding standards, branching strategies, and issue reporting to help contributors (from within Liquid Web or beyond) collaborate effectively on the plugin.
After adjusting the `v1.0.1-beta.2` tag that was pushed out Friday evening, this PR also restores the version number in the plugin header to "1.0.0" — on the next and subsequent beta releases, we'll bump this to "1.0.0 (Beta X)", and finally come back to 1.0.0 when we release the first official version.

Add contributing + changelog docs

---

.travis.yml
includes/class-wc-custom-order-table-cli.php
includes/class-wc-custom-order-table-install.php
includes/class-wc-custom-order-table.php
includes/class-wc-order-data-store-custom-table.php
phpcs.xml.dist
tests/test-installation.php
wc-custom-order-table.php

This branch cleans up some whitespace + documentation issues noted by PHP_CodeSniffer (no functional changes).
The last commit (cec0958) also removes the PHP_CodeSniffer portion of the Travis CI testing matrix, which _should_ let us start implementing PHPUnit against pull requests (I'm working on cleaning up some of the unescaped SQL issues — the last items still being caught by PHP_CodeSniffer — in a separate branch, since that means touching executable code.

PHP_CodeSniffer cleanup

---

includes/class-wc-custom-order-table-install.php
tests/test-installation.php

This PR adds indexes to the following columns in the existing schema, along with corresponding tests:
* order_key (unique) - used to identify the order within WooCommerce.
* customer_id - the WordPress user ID of the customer, or 0 if the order was a guest checkout. May be worth using a foreign key relationship in a later iteration.
* order_total - Available for sorting via the WooCommerce > Orders screen in wp-admin
The `WC_Custom_Order_Table_Install::$table_version property` has also been incremented.
Fixes #13.

Add indexes for the existing wp_woocommerce_orders table schema.

---

.travis.yml
README.md

This PR updates the test matrix for Travis CI in the following ways:
* Favor more modern versions of PHP for both speed and forwards-compatibility
* Never send email notifications
* Don't restrict Travis to running against `master`, as we want to use it for PRs, `develop`, and more.
Since we have a working build, I've also added the build status to the README file.

Make adjustments to the Travis CI configuration

---

tests/bootstrap.php
tests/test-bootstrap.php
tests/test-sample.php
wc-custom-order-table.php

The main goal of this PR is to ensure that the plugin doesn't bootstrap itself (via `wc_custom_order_table()`) until the `woocommerce_init` action (not `plugins_loaded`, as is happening currently).
Once `woocommerce_init` is responsible for bootstrapping the plugin, we can move away from the bundled, PHP 5.2-compatible autoloader much easier.
As our plugin will now require WooCommerce be present, we need to verify that WooCommerce is installed + active as part of the test suite. The resulting code in `tests/bootstrap.php` takes care of this, even automatically installing WooCommerce into the test environment if it doesn't already exist.
With this branch, the _first_ PHPUnit run will look something like this:
```
$ phpunit
Installing...
Running as single site... To run multisite, use -c …
```

Adjust plugin bootstrapping

---

.editorconfig
.gitignore
CONTRIBUTING.md
composer.json
includes/class-wc-order-data-store-custom-table.php
phpunit.xml.dist
tests/bootstrap.php
tests/test-data-store.php
tests/test-tools/class-wp-unittest-factory-for-customers.php
tests/test-tools/class-wp-unittest-factory-for-order.php
tests/test-tools/class-wp-unittest-factory-for-product.php
tests/testcase.php

This PR focuses on getting some tests around some of the functionality within `includes/class-wc-order-data-store-custom-table.php` — there's still a long way to go, but the focus is getting tests around anything that required refactoring for security (namely some poorly-prepared SQL statements).
This branch also introduces some additional WP core test suite factories: Customers, Orders, and Products. Now, much like we can generate posts within our tests via `$this->factory()->post->create()`, we can do the same for three key areas of WooCommerce.

Tests for the order data store

---

README.md
composer.json
includes/class-wc-custom-order-table-cli.php
includes/class-wc-custom-order-table.php
includes/class-wc-order-data-store-custom-table.php
phpcs.xml.dist
tests/bootstrap.php
tests/test-cli.php
tests/test-data-store.php
tests/test-tools/class-mock-progress-bar.php
tests/test-tools/class-wp-cli-command.php
tests/test-tools/class-wp-cli.php
tests/test-tools/utils.php
tests/testcase.php

This PR refactors the WP-CLI commands, adding tests and ensuring that data is reliably migrated back and forth between the custom orders and the post meta tables.
This PR also represents the last PHP_CodeSniffer violations for the project, so once merged all Travis tests should be passing (whoo!)
Fixes #27.

Refactor CLI command

---

composer.json
composer.lock
includes/class-wc-order-data-store-custom-table.php
phpunit.xml.dist
tests/test-data-store.php

Over the last week or so, [I've been opening PRs against WooCommerce](https://github.com/woocommerce/woocommerce/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Astevegrunwell) to help add test coverage for areas that query against order data in the postmeta table. While a number of these changes are still outstanding, I've updated the dev dependency for this project to use [the `liquidweb/woocommerce` fork on the `feature/more-order-tests` branch](https://github.com/liquidweb/woocommerce/tree/feature/more-order-tests); this branch merges each of the distinct feature branches into a "this is what we hope WooCommerce looks like if/when the PRs get accepted" branch.
Higher test coverage in those areas (mostly reporting) enables the WooCommerce Order Tables plugin to see other integration points …

Filter report data and act on the REST API system status indexing

---

.travis.yml
includes/class-wc-order-data-store-custom-table.php
tests/bin/set-woocommerce-version.sh
tests/bootstrap.php
tests/test-cli.php
tests/test-data-store.php
wc-custom-order-table.php

This PR adds the ability to have Travis run the test suite against multiple versions of WooCommerce, using the `WC_VERSION` environment variable (default is "latest", which maps to `dev-master`). Per @bswatson's recommendation, we're targeting the latest patch release of the current minor version (3.2.6 at the time of this writing).
Fixes #24.

Test against multiple versions of WooCommerce

---

README.md
composer.json
composer.lock
wc-custom-order-table.php

This PR removes the Composer-generated autoloader (and thus the requirement for site owners to run `composer install` to generate it) in favor of a direct [`spl_autoload()`](http://php.net/manual/en/function.spl-autoload.php) call.
Fixes #29.

Remove the Composer-generated autoloader

---

.travis.yml
CONTRIBUTING.md
README.md

This PR introduces [code coverage reporting through Coveralls](https://coveralls.io/github/liquidweb/woocommerce-custom-orders-table).
The test that runs code coverage is configured not to block Travis pass/fail determinations, [based on Travis' fast_finish directive](https://docs.travis-ci.com/user/customizing-the-build/#Fast-Finishing).
Current code coverage is about 97% 😄 
[![Coverage Status](https://coveralls.io/repos/github/liquidweb/woocommerce-custom-orders-table/badge.svg?branch=feature%2Fcode-coverage)](https://coveralls.io/github/liquidweb/woocommerce-custom-orders-table?branch=feature%2Fcode-coverage)

Code coverage reporting

---

.travis.yml
CHANGELOG.md
composer.json
composer.lock
includes/class-woocommerce-custom-orders-table-cli.php
tests/test-cli.php

This PR ensures that if `wc_get_order()` fails, the order is skipped in the migration.
Based on @zacscott's work in #44, add a test case and a simpler work-around for handling corrupted orders.
Fixes #43, closes #44. Props @zacscott.

Adjust importer to account for corrupted orders

---

.travis.yml

This PR adjusts the Travis CI build matrix to run the latest point release for each minor WooCommerce release >= 3.2 (plus master) on PHP 7.0 and higher. Additionally, PHP_CodeSniffer and Multisite tests are run against the "bleeding-edge" (PHP 7.2 + WooCommerce master), while code coverage is built against 7.1/master.
Also, it's worth mentioning that currently all builds running against master are failing, due to a bug in WooCommerce's master branch. [I've done some basic triage and reported it](https://github.com/woocommerce/woocommerce/pull/19436#issuecomment-374221195), but for now please don't let a failure on `WC_Tests_Product_Data_Store::test_search_products()` be considered grounds for not merging PRs.
WooCommerce master: [![Build status for …

Adjust Travis CI build matrix

---

includes/class-woocommerce-custom-orders-table.php

This is only relevant if https://github.com/woocommerce/woocommerce/pull/19436 is accepted, as currently tests for WC_Install::get_tables() are failing.
@bswatson If you get a moment to review and give it a 👍 that'd be appreciated, but without that PR in WooCommerce itself this doesn't do us any good.

Register the custom orders table within WooCommerce

---

tests/test-cli.php
tests/test-data-store.php

This PR adds some new tests, designed to _try_ to reproduce the duplicate ID errors reported in #49.
Unfortunately, I haven't been able to reproduce these (programmatically as tests nor through manually running the command), so I'm curious what other factors might be in play (or if the issue has already been fixed since the beta3 release).

Add tests to attempt to reproduce duplicate ID issues

---

composer.json
composer.lock
includes/class-wc-order-data-store-custom-table.php
tests/bootstrap.php
tests/test-data-store.php
tests/test-installation.php
tests/testcase.php

This PR aims to solve a few issues that have come up in testing, with the hopes of making the test suite less fragile as WooCommerce evolves:
[A number of our PRs have been merged into WooCommerce core](https://github.com/woocommerce/woocommerce/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Astevegrunwell), so there's no longer a need for our temporary `feature/more-orders-tests` branch.
Since the Custom Orders Table plugin relies on WooCommerce, let the WooCommerce core test suite bootstrap everything before we activate. This prevents incidents where, for example, a test run in isolation did not have access to the custom table.
This `else` statement was one level too high, causing issues when order queries were constructed with both `customer_emails` and `customer_ids` meta queries. Additional …

Refactor test suite

---

includes/class-woocommerce-custom-orders-table-cli.php
tests/test-cli.php

This PR leverages the "woocommerce_caught_exception" action to ensure that any exceptions that are raised during the execution of WooCommerce functions (such as `wc_get_order()`) are escalated and logged accordingly by WP-CLI.
Additionally, this PR lowers the default batch size for `migrate`/`backfill` from 1000 to 100, which results in more frequent database queries but a lower memory footprint, which will be important for less-powerful servers (such as in #49).
Fixes #56.

Handle exceptions during migration

---

.travis.yml
includes/class-wc-order-data-store-custom-table.php
includes/class-wc-order-refund-data-store-custom-table.php
includes/class-woocommerce-custom-orders-table.php
tests/test-core.php
tests/test-order-data-store.php
tests/test-order-refund-data-store.php

On a few different occasions (#49, #47, #58), users have reported errors similar to:
> Error: A database error occurred while migrating order XXX: Duplicate entry 'XXX' for key 'PRIMARY'
These errors were the result of `WC_Order_Data_Store_Custom_Table::$creating` not always being set properly, so the plugin would sometimes try to `INSERT` rather than `UPDATE` the corresponding database row.
Additionally, since the `WC_Order_Refund_Data_Store_Custom_Table` from #52 — which this PR depends upon — was largely copied from `WC_Order_Data_Store_Custom_Table` (I _really_ can't wait until we can use PHP traits in WordPress!), that class would have run into the same issue.
This PR simplifies the logic around the data stores' `update_post_meta()` methods, explicitly checking whether or not a …

Prevent duplicate IDs on order/refund save

---

composer.lock
phpunit.xml.dist
tests/test-cli.php

Newer releases of WooCommerce include a static `WP_HTTP_TestCase` method, which conflicts with our `CLITest::init()` (which is a `@before` method).
This PR renames the latter to `CLITest::init_cli()`.

Rename CLITest::init() to CLITest::init_cli() to avoid conflicting with WP_HTTP_TestCase::init()

---

.travis.yml
tests/compat.php
woocommerce-custom-orders-table.php

This commit also streamlines the construction of the Travis CI testing matrix: instead of defining each case individually, define a list of PHP versions and applicable combinations of environment variables.
Fixes #76.

Bump the 'WC tested up to' value to 3.5.0

---

README.md
composer.json
composer.lock
includes/class-woocommerce-custom-orders-table-cli.php
includes/class-woocommerce-custom-orders-table.php
tests/test-cli.php
tests/test-core.php
tests/test-order-data-store.php

This PR overhauls the migration script to clean up loops and provide more actionable feedback during migration.
Fixes #57, fixes #62. Blocked by #78.

Refactor the migration CLI command

---

includes/class-woocommerce-custom-orders-table-cli.php
tests/test-cli.php
tests/test-order-data-store.php

When a test creates multiple test orders within the same second, the resulting products cause MySQL to try to guess which order should come first rather than — as I had assumed — falling back to sorting by ID. As a result, ordering products by p.post_date alone cannot reliably keep two orders sorted the same way, since MySQL may decide to give precedence to any one of the rows with matching timestamps. Further details are [available in MySQL's "ORDER BY Optimization" documentation](https://dev.mysql.com/doc/refman/5.5/en/order-by-optimization.html).
This PR ensures that the `migrate` command explicitly falls back to sorting by `wp_posts.ID` in descending order, which matches the intent of "migrate the most recent orders (which are presumably more likely to be active) first, working …

Set an explicit fallback ORDER BY for the migrate command

---

includes/class-wc-order-data-store-custom-table.php
includes/class-wc-order-refund-data-store-custom-table.php
tests/test-order-data-store.php

WooCommerce stores customer-provided notes in the `wp_posts.post_excerpt` column rather than post meta, and overriding the order data store needs to preserve this behavior.
Fixes #68.

Ensure the customer_notes property is populated

---

woocommerce-custom-orders-table.php

The current autoloader implementation uses `set_include_path()`, which should be avoided.
Since PHP 5.3, there's no valid reason to use `set_include_path()` in application code anymore, as:
- it adds processing overhead and additional filesystem checks to _all_ `include`/`require` statements that follow it;
- following from that, it slows down _all_ other autoloaders as well;
- it can break in environments where the include path is set at the server level and cannot be changed due to security restrictions;
- `spl_autoload_register()` can be fed a callback that does the `include` directly, avoiding any further processing.
This alternative autoloader implementation uses a direct `include` in the callback that avoids the above drawbacks and is closer to the generally accepted approach that …

Replace autoloader implementation

---

README.md

The code coverage badge in the README should reflect coverage on `develop`, not `feature/code-coverage`.

Ensure the Coveralls badge is based on develop

---

includes/class-woocommerce-custom-orders-table-install.php
tests/test-installation.php

This PR changes the `customer_user_agent` column from a `VARCHAR(200)` to a `TEXT` column type, providing more space for longer User-Agent strings and fixing #89.
I'm choosing to **not** increment the database version here (since we're still pre-1.0.0) and the column type only needs to be changed if people are having problems with existing User-Agent strings > 200 characters. The change may manually be applied by doing either of the following:
1. Remove the `wc_orders_table_version` option from the site, letting WordPress automatically apply the transformation on the next request.
- This can be done via WP-CLI: `wp option delete wc_orders_table_version`
2. Run the following SQL query against the database: `ALTER TABLE wp_woocommerce_orders MODIFY customer_user_agent TEXT DEFAULT NULL …

Convert the customer_user_agent to a TEXT column type

---

.github/ISSUE_TEMPLATE/Bug_report.md
composer.json
composer.lock
includes/class-woocommerce-custom-orders-table-cli.php
phpcs.xml.dist

As reported in #92, users running PHP < 5.5 are seeing fatal errors [as `empty()` only worked on variables until PHP 5.5](http://php.net/manual/en/function.empty.php#refsect1-function.empty-parameters):
> **Note:** Prior to PHP 5.5, `empty()` only supports variables; anything else will result in a parse error. In other words, the following will not work: `empty(trim($name))`. Instead, use `trim($name) == false`.
This PR uses implicit type juggling for the loop, as well as updating Composer dependencies since the PHPCompatibility sniffs apparently didn't pick it up. I've also added "PHP Version" to the bug report template, to more easily identify bugs related to outdated PHP versions in the future.
Fixes #92.

Remove call to empty() on return from array_diff()

---

includes/class-wc-order-data-store-custom-table.php
tests/test-cli.php
tests/test-order-data-store.php

This PR supersedes #97 in addressing issues with duplicate order keys:
When saving an order to the custom table, an empty order key was being stored as `''` (an empty string), rather than explicitly being `NULL`. Since there's a `UNIQUE` key on that column, only one order could have an empty order key, and others would fail due to the uniqueness constraint.
This PR ensures that an empty order key is explicitly being cast as `NULL` as data is being prepared to go into the custom table, avoiding the table constraint.
Fixes #69, fixes #96.

Address duplicate order keys

---

.gitignore
.travis.yml
composer.json
composer.lock
woocommerce-custom-orders-table.php

Since it's been a couple months since we've been able to dedicate time to actively work on this plugin, I wanted to make sure we added PHP 7.3 and WooCommerce 3.5.2 to the Travis test matrix and generally update Composer dependencies.

Update development dependencies

---

.travis.yml
includes/class-woocommerce-custom-orders-table.php
tests/test-cli.php
tests/test-core.php
tests/test-order-data-store.php

When setting the billing email address for an order via `$order->set_billing_email()`, [WooCommerce verifies that the value evaluates as an email address](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-order.php#L1061). Since that value rarely (if ever) changes, users are only discovering that they have invalid emails in their databases when migrating into the custom orders table.
This PR will use Reflection to force the value *as it exists today* into the custom orders table. Additionally, other tests that relied on invalid emails triggering a `WC_Data_Exception` have been updated.
Fixes #98.

Don't let existing, invalid emails break migrations

---

includes/class-wc-order-refund-data-store-custom-table.php
includes/class-woocommerce-custom-orders-table.php

@stevegrunwell Oopsy-Doopsy :)
props. @phan

$table_data was in the wrong file

---

.travis.yml

Since WordPress doesn't yet *offically* support PHP 7.4, mark the tests as optional for now.
Based on a suggestion from @bswatson in #126.

Permit tests using PHP 7.4 to fail

---

includes/class-wc-order-data-store-custom-table.php
tests/test-filters.php

Fixes #125
`filter_database_queries` was being called before other plugins had a chance to include additional meta to the query. This resulted in the premature removal postmeta join from the query, which was causing the error.
This fix ensure the filter is executed at the last possible moment to ensure all plugins and themes have a chance to include meta data in the query.

Ensure the orders query is adjusted as late as possible.

---

includes/class-woocommerce-custom-orders-table.php

When setting meta, a method was called using a variable name (name of
meta). However, there may be non-standard meta fields, which cause a
fatal error when an attempt to call a non-existant method is used. To
prevent this there is now a check to ensure the method exists before
it is used.

Add method_exists check

---

composer.json
composer.lock
includes/Exceptions/QueryException.php
includes/Util/QueryIterator.php
includes/class-woocommerce-custom-orders-table-cli.php
phpcs.xml.dist
phpunit.xml.dist
tests/Util/QueryIteratorTest.php
woocommerce-custom-orders-table.php

This PR defines a new `QueryIterator` class, which is based on the `WP_CLI\Iterators\Query` class. Our iterator also extends the original, adding support for the `Countable` interface, along with better inline documentation and tests.
There are a few reasons for importing this into the project:
1. Leverage iterators rather than ad-hoc `while()` loops, with automatic support for adjusting offsets and creating corresponding `COUNT(*)` queries
2. Ensure that we have the iterator available regardless of whether or not WP-CLI is present on the target system. This will be important when it comes to #66
This PR duplicates some code from #159, and should be considered a blocker for that PR. It also is the first use of PSR-4 autoloading in the repository, which will eventually be the norm (see …

Introduce a new QueryIterator class

---

CHANGELOG.md
includes/class-wc-customer-data-store-custom-table.php
includes/class-woocommerce-custom-orders-table.php

Instead of adding the hooks in the constructor (potentially causing a *ton* of hooked callbacks), register the customer data store hooks once.

Only add the filters for WC_Customer_Data_Store_Custom_Table once

---

.travis.yml
phpunit.xml.dist
woocommerce-custom-orders-table.php

[Per our Compatibility Policy](https://github.com/liquidweb/woocommerce-custom-orders-table/blob/develop/CONTRIBUTING.md#compatibility-policy), we support the latest two releases of WordPress and latest 3 releases of WooCommerce. WooCommerce 4.0 is now available, which means our currently-supported WooCommerce releases are:
- 4.0
- 3.9
- 3.8

Bump WooCommerce requirements now that 4.0 is available
